# Generated by Django 5.1.11 on 2025-07-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_tenants", "0005_tenant_reputation_lower_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="enable_iframe_saml_logout",
            field=models.BooleanField(
                default=False,
                help_text="Enable iframe-based SAML logout. When enabled, SAML logout will use iframes for parallel logout. When disabled, redirect chain is used.",
            ),
        ),
    ]
