# Generated by Django 5.1.11 on 2025-07-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_stages_user_logout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlogoutstage",
            name="saml_logout_method",
            field=models.CharField(
                choices=[
                    ("redirect", "Redirect Chain"),
                    ("iframe", "Iframe (Parallel)"),
                    ("none", "Disabled"),
                ],
                default="redirect",
                help_text="Method to use for SAML provider logout",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userlogoutstage",
            name="saml_logout_timeout",
            field=models.IntegerField(
                default=5000, help_text="Timeout in milliseconds for SAML logout operations"
            ),
        ),
        migrations.AddField(
            model_name="userlogoutstage",
            name="saml_use_session_tracking",
            field=models.BooleanField(
                default=False,
                help_text="Only logout from SAML providers the user has active sessions with",
            ),
        ),
    ]
