# Generated by Django 5.1.12 on 2026-01-24

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_oauth2", "0031_remove_oauth2provider_backchannel_logout_uri_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingOAuth2Request",
            fields=[
                (
                    "expires",
                    models.DateTimeField(default=None, null=True),
                ),
                (
                    "expiring",
                    models.BooleanField(default=True),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Device ID from authentik_device cookie",
                        max_length=255,
                    ),
                ),
                (
                    "client_id",
                    models.CharField(max_length=255),
                ),
                (
                    "redirect_uri",
                    models.TextField(),
                ),
                (
                    "response_type",
                    models.CharField(max_length=50),
                ),
                (
                    "response_mode",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "_scope",
                    models.TextField(default="", verbose_name="Scopes"),
                ),
                (
                    "state",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "nonce",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "code_challenge",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "code_challenge_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "tab_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for the browser tab that created this request",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "is_leader",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this tab should handle interactive login",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent for validation"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="The OAuth2 provider for this pending request",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_providers_oauth2.oauth2provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending OAuth2 Request",
                "verbose_name_plural": "Pending OAuth2 Requests",
            },
        ),
        migrations.AddIndex(
            model_name="pendingoauth2request",
            index=models.Index(fields=["expires"], name="authentik_p_expires_pending_idx"),
        ),
        migrations.AddIndex(
            model_name="pendingoauth2request",
            index=models.Index(fields=["expiring"], name="authentik_p_expiring_pending_idx"),
        ),
        migrations.AddIndex(
            model_name="pendingoauth2request",
            index=models.Index(fields=["expiring", "expires"], name="authentik_p_exp_both_pending_idx"),
        ),
        migrations.AddIndex(
            model_name="pendingoauth2request",
            index=models.Index(fields=["device_id", "expires"], name="authentik_p_dev_exp_pending_idx"),
        ),
        migrations.AddIndex(
            model_name="pendingoauth2request",
            index=models.Index(fields=["device_id", "provider"], name="authentik_p_dev_prov_pending_idx"),
        ),
    ]
