# Generated by Django 5.1.12 on 2025-09-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_saml", "0020_samlprovider_backchannel_post_logout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="samlprovider",
            name="redirect_on_logout",
            field=models.BooleanField(
                default=False,
                help_text="authentik will redirect to the service provider after SP-initiated logout.",
                verbose_name="Redirect on logout",
            ),
        ),
    ]
